GadgetSecure/grails-app/controllers/gadgetsecure/UtilityController.groovy
package gadgetsecure

import grails.converters.JSON
import grails.plugin.springsecurity.annotation.Secured
import org.jsoup.Jsoup
import org.jsoup.nodes.Document
import org.jsoup.nodes.Element
import org.jsoup.select.Elements
import roles.UserType


class UtilityController {

    @Secured(['ROLE_ANONYMOUS'])
    def index() { }

    @Secured(['ROLE_ANONYMOUS'])
    def generateGadgetRegistrationReceipt(){
//        [employee: '248805']
    }

    @Secured(['ROLE_ANONYMOUS'])
    def downloadReceipt(){
        def invoice = Gadgets.findById(1)
        renderPdf(template: "template", model: [invoice: invoice],  filename: "Invoice.pdf")
    }

    @Secured(['ROLE_ANONYMOUS'])
    def becomeaDealer(){}

    @Secured(['ROLE_ANONYMOUS'])
    def viewPolicyDetails(){
        def invoice = Gadgets.findByPolicyNumber(params.policyNumber)

        render invoice as JSON
    }

    @Secured(['ROLE_ANONYMOUS'])
    def currentOpening(){}

    @Secured(['ROLE_ANONYMOUS'])
    def testScrap(){

    }

    @Secured(['ROLE_ANONYMOUS'])
    def jobDescription(){}

    @Secured(['ROLE_ANONYMOUS'])
    def submitDetail(){}

    @Secured(['ROLE_ANONYMOUS'])
    def faq(){}

    @Secured(['ROLE_ANONYMOUS'])
    def findSitemap(){}

    @Secured(['ROLE_ANONYMOUS'])
    def ticketStatus(){}

    @Secured(['ROLE_ANONYMOUS'])
    def buy(){}

    @Secured(['ROLE_ANONYMOUS'])
    def amazingService(){}

    @Secured(['ROLE_ANONYMOUS'])
    def getRsmPopup(){
        def data = RewardPopup.findByRole(UserType.findByUserType("RegionalSalesManager").id)
        render data as JSON
    }

    @Secured(['ROLE_ANONYMOUS'])
    def getCshPopup(){
        def data = RewardPopup.findByRole(UserType.findByUserType("CompanySalesHead").id)
        render data as JSON
    }

    @Secured(['ROLE_ANONYMOUS'])
    def getDistributorPopup(){
        def data = RewardPopup.findByRole(UserType.findByUserType("Distributor").id)
        render data as JSON
    }

    @Secured(['ROLE_ANONYMOUS'])
    def getDealerPopup(){
        def data = RewardPopup.findByRole(UserType.findByUserType("Dealer").id)
        render data as JSON
    }

    @Secured(['ROLE_ANONYMOUS'])
    def getSalesTeamPopup(){
        def data = RewardPopup.findByRole(UserType.findByUserType("SalesTeam").id)
        render data as JSON
    }

    @Secured(['ROLE_USER'])
    def buyform(){}

    @Secured(['ROLE_ANONYMOUS'])
    def saveFeedback(){
        println('[PARAMS] ' + params)

        FeedBack feed = new FeedBack()
        feed.review = params.review
        feed.rating = params.rating

        feed.save()

        render "success"

    }

    @Secured(['ROLE_ANONYMOUS'])
    def getPlanValue(){
        def data = GadgetPlans.findByPlanName(params.plan)
        render data as JSON

    }

    @Secured(['ROLE_ANONYMOUS'])
    def getPlans(){

        def data = GadgetPlans.list()

        render data as JSON

    }

    @Secured(['ROLE_ANONYMOUS'])
    def register(){}

    @Secured(['ROLE_ANONYMOUS'])
    def registerSuccess(){}

}

GadgetSecure/grails-app/views/utility/_template.gsp
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
    <title>Invoice</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

</head>
<body>
<div class="col-12">
    <!-- Page Content -->
    <div class="container">
    <p><center><rendering:inlineJpeg bytes="${logo}" /></center></p>

    <hr/>

    <div style="float: right;">
        <p><center><b><u>MEMBERSHIP NUMBER</u></b></center></p>
        <p><center><rendering:inlineJpeg bytes="${barcode}" /></center></p>
    </div>


    <table class="table table-bordered">
        <tr>
            <td style="line-height: 8px;text-transform: uppercase;">
                <p><b><u>ADDRESS</u></b></p>
                <p>${record.address}</p>
                <p>${record.city}</p>
                <p>${record.state}, ${record.pincode}</p>
                <p>${record.mobile}</p>
                <p><b>STATUS : </b>${record.status}</p>
            </td>
        </tr>
    </table>

    <hr/>

    <p>
        <b>Dear ${record.customerName},</b>
    </p>
    <p>
        Congratulations on buying Secure Gadget and welcome to the Secure Gadget
        family! We thank you for choosing to buy Secure Gadget and hope
        you will enjoy the benefits the membership offers.
    </p>

    <p>
        This welcome pack contains the following that explain all aspects of your
        Secure Gadget membership:
    </p>

    <p>
        <b>Benefit Guide:</b> Explains the key benefits of your membership in detail
    </p>
    <p> <b>Terms and Conditions:</b> Details the terms and conditions of your
    membership (including terms of your Equipment all risk insurance
    provided by the insurer)</p>
    <p> <b>Benefit usage instructions:</b> Easy-to-use instructions for benefits that are
    part of your membership.</p>
    <p>Your membership details along with the details of the asset purchased by
    you are mentioned overleaf. Don't hesitate to get in touch with us on the
    contact details mentioned for any assistance regarding your membership.</p>
    <p>Thank you again for becoming a Gadget Secure member!</p>
    Yours sincerely,<br/>
    For Gadget Secure<br/><br/>
    <p><rendering:inlineJpeg bytes="${sign}" style="width:150px;"/></p>
    </div>
    <!-- /.container -->
</div>
</body>
</html>

GadgetSecure/grails-app/views/utility/currentOpening.gsp
<%--
  Created by IntelliJ IDEA.
  User: shiva
  Date: 1/3/18
  Time: 12:08 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="customLayout"/>
    <asset:stylesheet src="jquery.dataTables_themeroller.css" />
    <asset:stylesheet src="jquery-ui.css" />
    <style>
    #example_info{
        display:none;
    }
    #example_length{
        margin-bottom: 2%;
    }
</style>
</head>

<body>
<asset:image src="j1.jpg" style="height: 400px; width: 100%;margin-bottom: 4%;"/>
%{--<div style="background-color:#6c757d;border-radius:30px;margin:3%">--}%
    %{--<form action="#" style="padding:30px" align="center" >--}%
        %{--<input type="text" name="jobkeyword" placeholder="Search by Job Keywords" style="width:40%">&nbsp;&nbsp;&nbsp;--}%
        %{--<input type="text" name="joblocation"placeholder="Search by Job Location" style="width:40%">&nbsp;&nbsp;&nbsp;--}%
        %{--<input type="button" value="Search" name="submit"  style="background-color:#721c24;width:8%;color: white;font-weight: bold;border-color: #721c24;border-radius: 5px">--}%
    %{--</form>--}%
%{--</div>--}%
<table id="example" class="display" cellspacing="0" width="70%" style="margin-bottom: 6%">
    <thead style="background-color: #cecece">
    <tr>
        <th>Title</th>
        <th>Location</th>
        <th>Experience</th>
        %{--<th>Job Description</th>--}%
        <th>Date</th>
        <th>Apply</th>
    </tr>
    </thead>



    <tbody id="job-list">



    </tbody>
</table>
<asset:javascript src="jquery.js" />
<asset:javascript src="jquery.dataTables.js" />
<script>
    $.noConflict();
    jQuery( document ).ready(function( $ ) {
        $('#example').DataTable();
    });
    // Code that uses other library's $ can follow here.

    var jobs = jQuery.parseJSON(jQuery.ajax({
        url:  "/Admin/getCurrentOpening",
        dataType: "json",
        async: false
    }).responseText);

    jQuery.each(jobs, function(i, item) {
        jQuery('#job-list').append('<tr><td>'+jobs[i].title+'</td><td>'+jobs[i].location+'</td><td>'+jobs[i].experiance+'</td><td>'+jobs[i].date+'</td><td><g:link controller="utility" action="submitDetail" class="btn btn-success btn-green">Apply</g:link></td></tr>');
    })

</script>
</body>
</html>

GadgetSecure/grails-app/views/utility/downloadReceipt.gsp
<%--
  Created by IntelliJ IDEA.
  User: kamesh
  Date: 6/2/18
  Time: 3:10 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
</head>

<body>

</body>
</html>

GadgetSecure/grails-app/views/utility/findSitemap.gsp
<%--
  Created by IntelliJ IDEA.
  User: shiva
  Date: 6/3/18
  Time: 10:27 AM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="customLayout"/>
    <style>
      #map {
        width: 100%;
        height: 400px;
        background-color: grey;
      }
    </style>
</head>
  </head>
  <body>
    <h3 style="text-align: center">Gadget Secure jabalpur</h3>


 <div id="map" style="width:80%;height:400px;background:yellow;margin-left: 10%;margin-right: 10%;margin-bottom: 5%"></div>

<script>
function myMap() {
    var myLatLng = new google.maps.LatLng(23.181467, 79.986407);
var mapOptions = {
    center:myLatLng,
    zoom: 5,
    mapTypeId: google.maps.MapTypeId.HYBRID
}
var map = new google.maps.Map(document.getElementById("map"), mapOptions);

        var contentString = '<div id="content">'+
            '<div id="siteNotice">'+
            '</div><asset:image src="logo.png" style="width: 10%;height: 30px" /> '+
            '<h5 id="firstHeading" class="firstHeading" style="color:red;display:inline;margin-left:5%">Gadget Secure Jabalpur</h5>'+
            '<div id="bodyContent" style="display:inline">'+
            '<p style="margin-left: 16%;margin-top: -1%;"><i class="fas fa-address-book"></i>&nbsp;&nbsp;<b>Gadget Secure</b>, Near Bhawartal Garden <b>Jabalpur</b>, 482001 ' +
            '<br /><br /><i class="fab fa-chrome"></i>&nbsp;&nbsp;www.gadgetsecure.com <br /><br />'+
            '<i class="fas fa-mobile-alt"></i>&nbsp;&nbsp;0761-123456/987654321<br /><br /> <i class="far fa-clock"></i>&nbsp;&nbsp;Opening Time- Mon - Sat (10:30am to 8:00pm)<br/> <span style="margin-left:19%">Sunday-Closed</span> <br/><span style="font-weight: bolder;color: #006dba">Rating : 8/10 <i class="fas fa-star" style="color: #f5bf02"></i><i class="fas fa-star" style="color: #f5bf02"></i><i class="fas fa-star" style="color: #f5bf02"></i><i class="fas fa-star" style="color: #f5bf02"></i><i class="far fa-star"></i></span></p>'+
            '</div>'+
            '</div>';

        var infowindow = new google.maps.InfoWindow({
          content: contentString
        });


  var marker = new google.maps.Marker({
    position: myLatLng,
    map: map,
    title: 'Gadget Secure, Near Bhawartal Garden, Jabalpur(M.P)-482001'
  });

          marker.addListener('click', function() {
          infowindow.open(map, marker);
        });

}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAyi5FbFIYB3VV2VC6AC6UVjnETGX9EPgc&callback=myMap"></script>

</body>
</html>

GadgetSecure/grails-app/views/utility/generateGadgetRegistrationReceipt.gsp
<%--
  Created by IntelliJ IDEA.
  User: kamesh
  Date: 5/2/18
  Time: 5:53 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="customLayout"/>

    %{--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>--}%
    %{--<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script>--}%
    %{--<script type="text/javascript">--}%
        %{--var doc = new jsPDF();--}%
        %{--var specialElementHandlers = {--}%
            %{--'#editor': function (element, renderer) {--}%
                %{--return true;--}%
            %{--}--}%
        %{--};--}%

        %{--$(document).ready(function() {--}%
            %{--$('#btn').click(function () {--}%
                %{--doc.fromHTML($('#content').html(), 15, 15, {--}%
                    %{--'width': 170,--}%
                    %{--'elementHandlers': specialElementHandlers--}%
                %{--});--}%
                %{--doc.save('sample-content.pdf');--}%
            %{--});--}%
        %{--});--}%
    %{--</script>--}%
</head>

<body>

%{--<div id="content">--}%
    %{--<h1><asset:image src="logo.png" style="width: 20%;"/></h1>--}%
    %{--<h1>Gadget Secure</h1>--}%
    %{--<p>Invoice Number : ${employee}</p>--}%

%{--</div>--}%

%{--<div id="editor"></div>--}%
%{--<button id="btn">Generate PDF</button>--}%

<g:link action="downloadReceipt">To PDF</g:link>

</body>
</html>

GadgetSecure/grails-app/views/utility/getCshPopup.gsp
<%--
  Created by IntelliJ IDEA.
  User: kamesh
  Date: 23/3/18
  Time: 1:20 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
</head>

<body>

</body>
</html>

GadgetSecure/grails-app/views/utility/getDealerPopup.gsp
<%--
  Created by IntelliJ IDEA.
  User: kamesh
  Date: 23/3/18
  Time: 1:26 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
</head>

<body>

</body>
</html>

GadgetSecure/grails-app/views/utility/getPlanValue.gsp
<%--
  Created by IntelliJ IDEA.
  User: kamesh
  Date: 20/3/18
  Time: 11:01 AM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
</head>

<body>

</body>
</html>

GadgetSecure/grails-app/views/utility/getPlans.gsp
<%--
  Created by IntelliJ IDEA.
  User: kamesh
  Date: 22/3/18
  Time: 2:32 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
</head>

<body>

</body>
</html>

GadgetSecure/grails-app/views/utility/registerSuccess.gsp
<%--
  Created by IntelliJ IDEA.
  User: shiva
  Date: 24/3/18
  Time: 6:42 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="customLayout"/>
</head>
<body>
    <h4 style="text-align: center;margin-top: 2%">Your are Successfully Registered</h4>
    <a href="/login/auth.gsp" style="color: blue;margin-left: 45%;margin-bottom: 2%;">Click here to login</a>
</body>
</html>

GadgetSecure/grails-app/views/utility/saveFeedback.gsp
<%--
  Created by IntelliJ IDEA.
  User: shiva
  Date: 17/3/18
  Time: 3:43 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
</head>

<body>

</body>
</html>

GadgetSecure/grails-app/views/utility/submitDetail.gsp
<%--
  Created by IntelliJ IDEA.
  User: shiva
  Date: 1/3/18
  Time: 3:06 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="customLayout"/>
</head>

<body>
<div>
<h4><b style="margin-left:35%">
    Career Opportunities: Submit the Detail</b></h4>
<form id="jobForm" enctype="multipart/form-data" method="post">
    <table class="table" align="center" style="width: 40%;">
        <tr>
            <td>
                Full Name*
            </td>
            <td>
                <input type="text" name="name" size="35%" class="form-control" id="name" placeholder="Enter Your Full Name">
            </td>
        </tr>
        <tr>
            <td>
                Email*
            </td>
            <td>
                <input type="email" name="email" size="35%" class="form-control" id="email" placeholder="Email Address">
            </td>
        </tr>
        <tr>
            <td>
                Retype Email Address*
            </td>
            <td>
                <input type="email" name="reemail" size="35%" class="form-control" placeholder="Email Address">
            </td>
        </tr>
        <tr>
            <td>
                Mobile No.*
            </td>
            <td>
                <input type="tel" name="mobile" size="35%" id="mobile" class="form-control" placeholder="Enter Your Mobile Number">
            </td>
        </tr>
        <tr>
            <td>
                Alternate Mobile No.*
            </td>
            <td>
                <input type="tel" name="altmobile" size="35%" id="altmobile"  class="form-control" placeholder="Enter Alternate Mobile Number">
            </td>
        </tr>
        <tr>
            <td>
                Aadhar Number*
            </td>
            <td>
                <input type="tel" name="aadhar" size="35%" id="aadhar" class="form-control" placeholder="Aadhar Number">
            </td>
        </tr>
        <tr>
            <td>
                Pincode*
            </td>
            <td>
                <input type="tel" name="pin" size="35%" id="pin" class="form-control" placeholder="Pincode">
            </td>
        </tr>
        <tr>
            <td>
                Please Attach Your Resume(.doc and .docx allowed)*
            </td>
            <td>
                <input type="file" class="form-control" name="file" />
            </td>
        </tr>
        <tr>
            <td>
                State of Residence
            </td>
            <td>
                <select aria-required="true" class="form-control" aria-label="State of Residence" id="state" name="state">

                    <option value="">SELECT STATE</option>
                 <option value="Andaman and Nicobar Islands">Andaman and Nicobar Islands</option>
                    <option value="Andhra Pradesh">Andhra Pradesh</option>
                    <option value="Arunachal Pradesh">Arunachal Pradesh</option>
                    <option value="Assam">Assam</option>
                    <option value="Bihar">Bihar</option>
                    <option value="Chandigarh">Chandigarh</option>
                    <option value="Chhattisgarh">Chhattisgarh</option>
                    <option value="Dadra and Nagar Haveli">Dadra and Nagar Haveli</option>
                    <option value="Daman and Diu">Daman and Diu</option>
                    <option value="Delhi">Delhi</option>
                    <option value="Goa">Goa</option>
                    <option value="Gujarat">Gujarat</option>
                    <option value="Haryana">Haryana</option>
                    <option value="Himachal Pradesh">Himachal Pradesh</option>
                    <option value="Jammu and Kashmir">Jammu and Kashmir</option>
                    <option value="Jharkhand">Jharkhand</option>
                    <option value="Karnataka">Karnataka</option>
                    <option value="Kerala">Kerala</option>
                    <option value="Lakshadweep">Lakshadweep</option>
                    <option value="Madhya Pradesh">Madhya Pradesh</option>
                    <option value="Maharashtra">Maharashtra</option>
                    <option value="Manipur">Manipur</option>
                    <option value="Meghalaya">Meghalaya</option>
                    <option value="Mizoram">Mizoram</option>
                    <option value="Nagaland">Nagaland</option>
                    <option value="Orissa">Orissa</option>
                    <option value="Pondicherry">Pondicherry</option>
                    <option value="Punjab">Punjab</option>
                    <option value="Rajasthan">Rajasthan</option>
                    <option value="Sikkim">Sikkim</option>
                    <option value="Tamil Nadu">Tamil Nadu</option>
                    <option value="Tripura">Tripura</option>
                    <option value="Uttaranchal">Uttaranchal</option>
                    <option value="Uttar Pradesh">Uttar Pradesh</option>
                    <option value="West Bengal">West Bengal</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>
                Select Job Title
            </td>
            <td>
                <select aria-required="true" aria-label="State of Residence" class="form-control" id="jobId" name="jobId">
                    <option value="">SELECT Job Title</option>
                </select>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" class="btn btn-warning btn-block"  onclick="submitPersonalDetail()"  style="background-color:#721c24;color:white;border-color: #721c24;border-radius: 5px;margin-left: 40%;width: 17%">
            </td>
        </tr>
    </table>
</form>
<h3 id="msg" style="text-align: center;font-weight: bolder;color: green"></h3>
</div>
<asset:javascript src="jquery.min.js"/>
<script>

    var jobs = jQuery.parseJSON(jQuery.ajax({
        url:  "/Admin/getCurrentOpening",
        dataType: "json",
        async: false
    }).responseText);

    jQuery.each(jobs, function(i, item) {
        $('#jobId').append('<option value="'+jobs[i].id+'">'+jobs[i].title+'</option>');
    })

   // var states = jQuery.parseJSON(jQuery.ajax({
   //      url:  "/Admin/getStates",
   //      dataType: "json",
   //      async: false
   //  }).responseText);
   //
   //  jQuery.each(states, function(i, item) {
   //      $('#state').append('<option value="'+states[i].state+'">'+states[i].state+'</option>');
   //  })

    function submitPersonalDetail(){


        var name=$('#name').val();
        var email=$('#email').val();
        var mobile=$('#mobile').val();
        var aadhar = $('#aadhar').val();
        var pin = $('#pin').val();
        var state = $('#state').val();
        var jobId = $('#jobId').val();
        // var status = $.parseJSON($.ajax({
        //     url:  "/Admin/saveJobApplication?name="+name+"&email="+email+"&mobile="+mobile+"&altmobile="+$('#altmobile').val()+"&aadhar="+aadhar+"&pin="+$('#pin').val()+"&state="+$('#state').val()+"&jobid="+$('#jobId').val()+"",
        //     dataType: "json",
        //     async: false
        // }).responseText);

        if(name !== "" && email !== "" && mobile !== "" && aadhar !== "" && pin !== "" && state !== "" && jobId !== ""){
            console.log('SUBMITTED');
            $("#jobForm").attr("action", "/Admin/saveJobApplication");
            $('#jobForm').submit();
        }
        else{
            alert('All Feilds are Mandatory');
            console.log('!SUBMITTED');
            return false;

        }

        // debugger
        // if(status[0] === 'success'){
        //     /*$('#newForm')[0].reset();*/
        //     alert(status[0])
        //     $('#msg').html('successfully submitted!')
        // }else{
        //
        // }
    }


</script>
</body>
</html>

GadgetSecure/grails-app/views/utility/ticketStatus.gsp
<%--
  Created by IntelliJ IDEA.
  User: shiva
  Date: 8/3/18
  Time: 4:37 PM
--%>


<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="customLayout"/>
</head>

<body>




<div class="col-6" style="margin-left: 26%;margin-top: 10%; margin-bottom: 20%;">
    <fieldset>
        <legend style="color: #d51a21;">Ticket Status </legend>

        <form action="#" method="get">
            <div class="form-group">
                <label for="policyNumber"></label>
                <input type="text" class="form-control" id="policyNumber" name="policyNumber" placeholder="Enter Ticket Number" style="margin-top: -3%">
                %{--<small id="emailHelp" class="form-text text-muted">PLEASE ENTER IMEI/MAC OF YOUR PROTECTED GADGET</small>--}%
            </div>

            <input type="submit" class="btn btn-danger" value="<g:message code="app.claim.index.submit" />" />
        </form>

    </fieldset>

</div>
</body>
</html>

GadgetSecure/grails-app/views/utility/viewPolicyDetails.gsp
<%--
  Created by IntelliJ IDEA.
  User: kamesh
  Date: 20/2/18
  Time: 1:50 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
</head>

<body>

</body>
</html>